---
Name: insite
After:
  - 'framework/*'
  - 'cms/*'
---

SiteConfig:
  extensions:
    - InsiteApps\SocialMedia\SocialMediaExtension
    - InsiteApps\SocialMedia\SocialMediaSiteConfigExtension

Page:
  extensions:
    - InsiteApps\SocialMedia\SocialMediaPageExtension

Page_Controller:
  extensions:
    - InsiteApps\SocialMedia\SocialMediaPageControllerExtension
