---
Name: insite
After:
  - 'framework/*'
  - 'cms/*'
---

SiteConfig:
  extensions:
    - SocialMediaExtension
    - SocialMediaSiteConfigExtension

Page:
  extensions:
    - SocialMediaPageExtension

Page_Controller:
  extensions:
    - SocialMediaPageControllerExtension
